spring.application.name=web-iglesia
server.address=0.0.0.0
server.port=8092
#configuracion de la sona horaria
#spring.jackson.time-zone=UTC
spring.jackson.time-zone=America/La_Paz



# Configuración de la base de datos MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3307/iglev3
spring.datasource.username=root
spring.datasource.password=root

# Dialecto de MariaDB para JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=update


# 1. Nivel general en INFO para evitar el ruido de Java y RMI
logging.level.root=DEBUG

# 2. DEBUG solo para tu proyecto
# (Asumiendo que tus clases empiezan con 'com.webiglesia' o similar)
logging.level.com.web-iglesia=DEBUG

# 3. Silenciadores específicos para lo que te salía cada segundo
logging.level.sun.rmi=OFF
logging.level.javax.management=OFF


#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Forzar a Hibernate a usar los nombres tal como están en las anotaciones
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Configuración JWT
jwt.secret.key=c1fea328766dc1e80b7aa8b5ca2498c443a3db543f6d99c4b1955f9cf5d6a05e
jwt.time.expiration=86400000
#cuanto es un dia  en milisegundos = 86400000

# Configuración para Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Configuración para la subida de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads
file.base-url=http://localhost:8092

# Si se debe lanzar una "NoHandlerFoundException" si no se encontró ningún controlador para procesar una solicitud.
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

server.max-http-request-header-size=64KB
