# Configuración Local (MariaDB Local)
spring.datasource.url=jdbc:mariadb://localhost:3307/iglev3
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# Logs detallados para desarrollo
logging.level.root=INFO
logging.level.com.web-iglesia=DEBUG

# JWT y URL locales
jwt.secret.key=clave_de_desarrollo_muy_debil_12345
jwt.time.expiration=86400000
file.upload-dir=uploads
file.base-url=http://localhost:8092