# Configuración de Producción
spring.datasource.url=jdbc:mariadb://${DB_HOST}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# En producción no queremos que Hibernate borre o altere tablas automáticamente
spring.jpa.hibernate.ddl-auto=validate

# Logs limpios
logging.level.root=WARN
logging.level.com.web-iglesia=INFO

# Seguridad Real
jwt.secret.key=${JWT_SECRET_PROD}
jwt.time.expiration=86400000
file.upload-dir=${PROD_STORAGE_PATH}
file.base-url=${PROD_DOMAIN_URL}